---
# Source: ui/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: opk-ui-secret
type: Opaque
data:
  REDIS_USER: redis 
  REDIS_PASSWORD: redis
---
# Source: ui/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opk-ui-configmap
data:
  REDIS_HOST: redis-master
  AUTH_HOST: opk-auth-service
  AUTH_PORT: 8080
  WEATHER_PORT: 5000
  WEATHER_HOST: opk-weather-service
  REDIS_PORT: 6379
---
# Source: ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: opk-ui-service
  annotations: 
    alb.ingress.kubernetes.io/healthcheck-path: /index.html
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: opk-ui
---
# Source: ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opk-ui

spec:
  replicas: 1
  selector:
    matchLabels:
      app: opk-ui
      opk: weather
  template:
    metadata:
      labels:
        app: opk-ui
        opk: weather
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: opk-ui
          securityContext:
            {}
          image: "prinsoo/weather-app:ui.v1"
          imagePullPolicy: IfNotPresent
          env:
            - name: AUTH_HOST
              valueFrom:
                configMapKeyRef:
                  name: opk-ui-configmap
                  key: AUTH_HOST
            - name: AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: opk-ui-configmap
                  key: AUTH_PORT
            - name: WEATHER_HOST
              valueFrom:
                configMapKeyRef:
                  name: opk-ui-configmap
                  key: WEATHER_HOST
            - name: WEATHER_PORT
              valueFrom:
                configMapKeyRef:
                  name: opk-ui-configmap
                  key: WEATHER_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: opk-ui-configmap
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opk-ui-secret
                  key: REDIS_PASSWORD
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {}
---
# Source: ui/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "ui-test-connection"
  labels:
    helm.sh/chart: ui-0.1.0
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: ui
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['ui:3000']
  restartPolicy: Never
