apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}-secret
type: Opaque
data:
  REDIS_USER: {{ .Values.credentials.REDIS_USERNAME }} 
  REDIS_PASSWORD: {{ .Values.credentials.REDIS_PASSWORD }}