apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}-secret
type: Opaque
data:
  REDIS_USER: {{ .Values.credentials.REDIS_USER }}
  AUTH_HOST: {{ .Values.credentials.AUTH_HOST }}
  AUTH_PORT: {{ .Values.credentials.AUTH_PORT }}
  WEATHER_PORT: {{ .Values.credentials.WEATHER_PORT }}
  WEATHER_HOST: {{ .Values.credentials.WEATHER_HOST }}
  REDIS_PASSWORD: {{ .Values.credentials.REDIS_PASSWORD }}