apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-service
  annotations: 
    alb.ingress.kubernetes.io/healthcheck-path: /index.html
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app_name}}
