apiVersion: apps/v1
kind: Deployment
metadata:
  name: thomosis-auth
  labels:
    app: thomosis-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thomosis-auth  
  template:
    metadata:
      labels:
        app: thomosis-auth
    spec:
      serviceAccountName: thomosis-service-account  # Add this line
      containers:
        - name: thomosis-auth
          image: devopseasylearning/thomisis-auth:v0.0.1
          env:
            - name: DB_HOST
              value: db
            - name: DB_PASSWORD
              value: my-secret-pw
            # - name: DB_USER
            #   value: auth
          resources:
            requests:
              memory: "256Mi"   # Set the initial memory request
              cpu: "100m"       # Set the initial CPU request
            limits:
              memory: "2Gi"   # Set the maximum memory limit
              cpu: "600m"       # Set the maximum CPU limit
