apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thomosis-db
  labels:
    app: thomosis-db
spec:
  serviceName: thomosis-db
  replicas: 1
  selector:
    matchLabels:
      app: thomosis-db
  template:
    metadata:
      labels:
        app: thomosis-db
    spec:
      containers:
        - name: thomosis-db
          image: devopseasylearning/thomisis-db:v0.0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my-secret-pw
            - name: MYSQL_DATABASE
              value: db
            # - name: MYSQL_USER
            #   value: auth
            # - name: MYSQL_PASSWORD
            #   value: my-secret-pw
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: opk-sc
        resources:
          requests:
            storage: 5Gi
